### PR TITLE
Add common-section-card component

### PR DESCRIPTION
**Pull request by zackcl**
This PR creates a common section card component that renders header, content, and footer.

### CODE REVIEW

**Comment by zackcl** [comment]
@danoswaltCL I applied the change you suggested to remove the `hasFooter`.

**Comment by danoswaltCL** [comment]
no base styles?

**Comment by zackcl** [comment]
@danoswaltCL I will create a separate PR to add the styles soon.

**Review by VivekFitkariwala — APPROVED** [review]

**Review by Yagnik56 — APPROVED** [review]
looks good

**Pull request merged**
