### PR TITLE
Displaying the number of groups having met ending criteria for the group experiment

### PR DESCRIPTION
**Pull request by YashilDepani**
This PR is about **displaying the number of groups that have met the ending criteria for the group experiment**. We were not having the information of how many groups have actually completed the `ending-criteria` and how close is the experiment to being changed to `enrollment-complete` state.
 
In the ending criteria dialogue box, a line below displays the number of groups. This is only for the group experiments with ending criteria depending upon the number of groups.

 I created a group experiment with ending criteria as 2 groups and 2 participants per group.
 The first image displays the initial state of the experiment. As currently no participants have been involved, the group count is zero.
 In the second image, after involving two users with the below information, the group count is now 1. This is because in the school1 group, two participants have been enrolled.
```
"group": {
       "add-group1": ["school1"]
   },
   "workingGroup": {
       "add-group1": "school1"
    }
```
 In the third image, after involving two users with the below information, the group count is now 2. The experiment state also changed to `enrollment-complete` state.
```
"group": {
       "add-group1": ["school2"]
   },
   "workingGroup": {
       "add-group1": "school2"
    }
```
image
image
image

### CODE REVIEW

**Review by amurphy-cl — CHANGES_REQUESTED** [review]
Let's hold off merging this and other code-heavy PRs until #304 is fixed, as a sort of temporary "code freeze" while we try to resolve the major issues preventing us from running UpGrade in prod.

**Comment by amurphy-cl** [comment]
@danoswaltCL I guess since the client app build for today failed we can probably go ahead and merge this now.

**Comment by YashilDepani** [comment]
Let us not merge this PR. The merger of this PR  will create merge conflicts for my branch. I will be soon creating PR for this [issue](https://github.com/CarnegieLearningWeb/UpGrade/issues/304) as this is the priority.

**Comment by ppratikcr7** [comment]
> Let us not merge this PR. The merger of this PR will create merge conflicts for my branch. I will be soon creating PR for this [issue](https://github.com/CarnegieLearningWeb/UpGrade/issues/304) as this is the priority.

@YashilDepani I guess now we can merge this?

**Comment by ppratikcr7** [comment]
@jreddig Hey Jenn, can you once try to pull dev branch in this PR branch and check for the jest test cases failing. I tried to resolve it, but unable to resolve it. I have added the missing dependencies for the RootTestModule context (ExperimentService, ExperimentConditionRepository and QueryRepository). Still it says that we are missing the 12th argument dependency from ExperimentService (i.e. ScheduledJobService). And ScheduledJobService is already present in the dependencies. 
Screenshot 2022-05-10 at 12 30 46 PM

**Review by ppratikcr7 — COMMENTED** [review]
Jest test cases are failing when merged with latest dev

**Comment by jreddig** [comment]
> 

Looking into this now. I think it's a circular dependency since the error doesn't say `ScheduledJobService`. I believe the dependency is undefined, which is why it's called `dependency`

**Comment by danoswaltCL** [comment]
on frontend, it just looks like a typescript compilation error because the `Experiment` type was updated to require a new `groupSatisfied` field.

https://github.com/CarnegieLearningWeb/UpGrade/pull/305/files#diff-56573ca5909dd79cb81397e51a992f856e385b97f3b96f0c3e40377b3821d20f

so any mock data of `Experiment` type needs to have that field included now also.

**Comment by danoswaltCL** [comment]
@jreddig @ppratikcr7 I made changes on local to just add 'groupsSatisfied: 0' field to mock "Experiment" type data in failing frontend tests.

Then in the `SupportService.test.ts` spec, the dependencies are properly mocked out with spies, so one ditch the testingmodule / providers altogether and just go with vanilla js/typescript for a straightforward simple test.

`beforeEach(async () => {
        service = new SupportService({} as ExperimentAssignmentService, {} as ExperimentUserService)
    })`
    
    Tests pass in my local, but there's some other issue with Integration tests failing, not sure what that's about. I can push up this commit with `--no-verify` if you want to get around the integration tests, I'm not sure if you're seeing those fail or if it's just something on my local (it's been a while since I've run upgrade locally, maybe i'm forgetting a step)

**Comment by amurphy-cl** [comment]
Is this PR still relevant now that the enrollment counts are going to be generated via table rather than joins?

**Comment by ppratikcr7** [comment]
> on frontend, it just looks like a typescript compilation error because the `Experiment` type was updated to require a new `groupSatisfied` field.
> 
> https://github.com/CarnegieLearningWeb/UpGrade/pull/305/files#diff-56573ca5909dd79cb81397e51a992f856e385b97f3b96f0c3e40377b3821d20f
> 
> so any mock data of `Experiment` type needs to have that field included now also.

Yeah, I had added that to mockdata. But, the issue is the missing dependency.

**Comment by ppratikcr7** [comment]
> Confirmed -- The circular dependency between `ExperimentService` and `ScheduledJobService` is causing the provider error. This was caused by adding a dependency on `ExperimentService` in `ExperimentAssignmentService`. Is there a way to do `getGroupAssignmentStatus` without using `ExperimentService`?

Yes, that's the exact issue. Probably we can bypass this by using the new enrollment table once that's merged.

**Comment by ppratikcr7** [comment]
> @jreddig @ppratikcr7 I made changes on local to just add 'groupsSatisfied: 0' field to mock "Experiment" type data in failing frontend tests.
> 
> Then in the `SupportService.test.ts` spec, the dependencies are properly mocked out with spies, so we can ditch the testingmodule / providers altogether and just go with vanilla js/typescript for a straightforward simple test.
> 
> `beforeEach(async () => { service = new SupportService({} as ExperimentAssignmentService, {} as ExperimentUserService) })`
> 
> Tests pass in my local, but there's some other issue with Integration tests failing, not sure what that's about. I can push up this commit with `--no-verify` if you want to get around the integration tests, I'm not sure if you're seeing those fail or if it's just something on my local (it's been a while since I've run upgrade locally, maybe i'm forgetting a step)

Let me try this out in my local. Thanks Dan

**Comment by ppratikcr7** [comment]
> Is this PR still relevant now that the enrollment counts are going to be generated via table rather than joins?

We can use the frontend code part and update the backend code as per the new enrollment table, once it's merged in dev.

**Review by ppratikcr7 — APPROVED** [review]

**Comment by danoswaltCL** [comment]
@amurphy-cl i think you have a comment from way far back that needs resolved before this can be merged

**Review by amurphy-cl — APPROVED** [review]

**Pull request merged**
