### PR TITLE
Adding Simple Export

### PR DESCRIPTION
**Pull request by ppratikcr7**

### CODE REVIEW

**Review by jreddig — APPROVED** [review]
This looks good in my local! I will fix/update the unit tests if things break when merging in dev

**Comment by VivekFitkariwala** [comment]
PR is updated with two fields
FirstDecisionPointReached_On
FirstDecisionPointReachedOn_LocalTime

Now we are saving the localTimeZone of portal user in the database

**Review by jreddig — COMMENTED** [review]
Looks good! 
I just think we want both timestamps to be in the same format. Personally, I like '8/12/2022, 10:25:18 AM' over 'Fri, 12 Aug 2022 14:25:18 GMT'

**Comment by VivekFitkariwala** [comment]
As per discussion updated the date format to ISO

**Review by jreddig — DISMISSED** [review]

**Review by jreddig — APPROVED** [review]

**Pull request merged**
