### PR TITLE
Detail-Page-Tab-View

### PR DESCRIPTION
**Pull request by Yagnik56**
I have changed detail page view as per figma design with 4 tabs with data tab instead of view data button like @zackcl shared recently in design group.

### CODE REVIEW

**Comment by danoswaltCL** [comment]
hi @Yagnik56 I will try to get a review to you this this week. we are focused on testing out release code at the moment, maybe @zackcl will need to take a look after his vac this week anyway though since he did the design changes. thank you!

**Comment by Yagnik56** [comment]
Here are few screenshots to get better idea about update. 
Data:
image

Overview:
image

Design:
image

Participants:
image

Metrics:
image

**Comment by zackcl** [comment]
Sorry for the delay, I will review this soon.

**Comment by zackcl** [comment]
@Yagnik56 I just reviewed this branch, great work!

I notice 2 things that need to be updated:

1. The "POST RULE" appears at the top of the tabs for some reason, so this should be removed.
Screen Shot 2022-10-25 at 11 58 13 AM

2. The "Data" tab should appear once the experiment status is set to "Enrolling". Until then, there should only be 4 tabs without the "Data" tab (And the default tab should always be the "Overview" tab - the user should be in this tab after creating an experiment and also changing the status to "Enrolling").
Screen Shot 2022-10-25 at 12 08 43 PM

Also, there should be an "Aliases" table in the "Design" tab but maybe this can be updated with another PR.
Experiment Detail - Design (Enrolling)

Here you can find the latest design in Figma: https://www.figma.com/file/uYxnCT2dXTftSZKFQ00Q0y/UpGrade-UI-Prototype-(latest). If you have any questions, please feel free to ask.

**Comment by Yagnik56** [comment]
Sorry for delay @zackcl  and many commits, there were some conflicts in few files. 

The "POST RULE" on top section was one of conflict with dev, it's resolved now.
I have made changes for data tab according to your 2nd point and kept overview tab as default. 

I have switched between experiment states to verify changes, you can find few images for same below.
image

image

image

let me know if any changes required.

**Comment by danoswaltCL** [comment]
@Yagnik56 I will resolve these conflicts on what is in github today. If you have work that has not been pushed up, let me know and we can work through those merge conflicts as well if need be.

**Comment by zackcl** [comment]
@Yagnik56 Sorry for the delay, I just tried this and it seems to work fine functionally.

But style-wise, I would like to suggest using the same font used for tabs on the other pages in UpGrade (e.g. Logs, Profile) for consistency.

Screen Shot 2022-11-07 at 1 53 24 PM


For example, the font should be "Open Sans" with a 22px size and 600 weight. Also, when a tab is clicked, the grey selection box should be transparent. Lastly, the text should not change to light blue when the tab loses focus (by clicking somewhere else).

I think it should be good to be merged after these small changes. Thanks for the great work!

**Comment by Yagnik56** [comment]
> @Yagnik56 Sorry for the delay, I just tried this and it seems to work fine functionally.
> 
> But style-wise, I would like to suggest using the same font used for tabs on the other pages in UpGrade (e.g. Logs, Profile) for consistency.
> 
> Screen Shot 2022-11-07 at 1 53 24 PM
> 
> For example, the font should be "Open Sans" with a 22px size and 600 weight. Also, when a tab is clicked, the grey selection box should be transparent. Lastly, the text should not change to light blue when the tab loses focus (by clicking somewhere else).
> 
> I think it should be good to be merged after these small changes. Thanks for the great work!

@zackcl I haven't made any changed in Logs, I have only addressed tab view in experiment section only. should I make changes on Logs as well? also I didn't understand grey selection box, can you share pic where change is required!

**Comment by Yagnik56** [comment]
@zackcl I have made changes you mentioned, let me know if any other changes required otherwise we can merge it with dev.

**Comment by zackcl** [comment]
@Yagnik56 I think it looks good now. 

But in terms of hiding/showing the Data tab, we just decided to make it always visible and place it next to the Metrics tab so that it's basically like the current details page but with tabs (because hiding it can be a little confusing). 

Experiment Detail - Data (Enrolling) 79


You can check out the [slack post](https://carnegielearning.slack.com/archives/C02QA168MNW/p1668011132608659) where we discussed this. Steve Ritter also mentioned, "If there’s no data, we could just display `no data received yet`" but I personally don't think it's necessary for now because the user can still know there's no data if the participant enrollment is 0.

**Comment by Yagnik56** [comment]
> @Yagnik56 I think it looks good now.
> 
> But in terms of hiding/showing the Data tab, we just decided to make it always visible and place it next to the Metrics tab so that it's basically like the current details page but with tabs (because hiding it can be a little confusing).
> 
> Experiment Detail - Data (Enrolling) 79
> 
> You can check out the [slack post](https://carnegielearning.slack.com/archives/C02QA168MNW/p1668011132608659) where we discussed this. Steve Ritter also mentioned, "If there’s no data, we could just display `no data received yet`" but I personally don't think it's necessary for now because the user can still know there's no data if the participant enrollment is 0.

@zackcl I have put data tab as it was in last, removed hiding setting when exp.state isn't enrolling.

**Comment by zackcl** [comment]
@Yagnik56 Sorry I was a little busy today, I will review this tomorrow. Thanks!

**Review by zackcl — APPROVED** [review]

**Pull request merged**
