### PR TITLE
add quicktests for the clientlibs

### PR DESCRIPTION
**Pull request by danoswaltCL**
This improves usability of the Main.java test script, renaming it to `QuickTest.java`, matching the style of the ts `quickTest.ts` file.
 
These can be used to smoke test the client libs on the release branch on our deployed envs.

The "log" call for the Java client lib seems to have something off with its response, but since it is not a feature anybody uses at the moment, and because the response is not important at all anyway, I have commented it out, will spawn issue.

### CODE REVIEW

**Comment by bcb37** [comment]
> The "log" call for the Java client lib seems to have something off with its response, but since it is not a feature anybody uses at the moment, and because the response is not important at all anyway, I have commented it out, will spawn issue.

Is that different from [this issue](https://github.com/CarnegieLearningWeb/UpGrade/issues/1024)

**Review by bcb37 — APPROVED** [review]
This worked for me. I have a fix for the log method. Can make a pr.

**Comment by danoswaltCL** [comment]
@bcb37 Yeah do you want to commit to this branch if you know a fix for that? could easily be same basic issue. I was being lazy and didn't look into it very deeply.

**Comment by danoswaltCL** [comment]
cool, works for me if you want to approve, i'll pr to merge down to dev also.

**Review by bcb37 — APPROVED** [review]

**Pull request merged**
