### PR TITLE
✨ Enhancement/1133 backend packages update Part3

### PR DESCRIPTION
**Pull request by ppratikcr7**
This PR made the following modifications to the backend dependencies:

**Added:**

> @types/supertest (Required by supertest package)

**Removed:**

> npm (Not required in Upgrade project, was maybe installed by mistake)
> @types/helmet (Not required in latest helmet package)

**Updated:**

> @aws-sdk/client-s3
> @aws-sdk/client-ses
> @aws-sdk/client-sfn
> @aws-sdk/lib-storage
> @aws-sdk/s3-request-presigner
> cache-manager
> iso8601-duration
> newrelic
> ts-node
> @types/node
> @types/express
> @types/express-serve-static-core
> @types/cors
> @types/jest
> @nestjs/common
> @nestjs/testing
> @nestjs/typeorm
> typescript

**Note:** As per the helmet changelog from v3 to v4 the `helmet.noCache` was removed because it isn’t directly relevant to security. So, the `SecurityNoCacheMiddleware` is not required and supported in versions after v3 of helmet. Refer [this](https://helmetjs.github.io/faq/helmet-4-upgrade/).

### CODE REVIEW

**Review by VivekFitkariwala — DISMISSED** [review]

**Review by danoswaltCL — APPROVED** [review]
looks good to me, i'd merge but a couple of conflicts in the package.jsons

**Comment by ppratikcr7** [comment]
> looks good to me, i'd merge but a couple of conflicts in the package.jsons

Okay, will resolve them. The other backend package update PR is now merged in dev, so need to resolve conflicts here. I have also updated nestjs packages now in this PR.

**Comment by ppratikcr7** [comment]
@danoswaltCL @bcb37 Now we are left with 4 backend packages to be updated. @RidhamShah  is working on typedi, reflect-metadata and typeorm. We tried to update sinon, but there is some issues with unit test cases. Also, we were thinking why are we using both sinon and jest for unit test cases. We should use only one, most likely jest. What do you think? Any reason why we are using sinon?

**Comment by ppratikcr7** [comment]
@danoswaltCL @bcb37 Now we are left with 4 backend packages to be updated. @RidhamShah  is working on typedi, reflect-metadata and typeorm. We tried to update sinon, but there is some issues with unit test cases. Also, we were thinking why are we using both sinon and jest for unit test cases. We should use only one, most likely jest. What do you think? Any reason why we are using sinon?
Screenshot 2023-12-22 at 1 42 38 AM

**Comment by danoswaltCL** [comment]
> @danoswaltCL @bcb37 Now we are left with 4 backend packages to be updated. @RidhamShah is working on typedi, reflect-metadata and typeorm. We tried to update sinon, but there is some issues with unit test cases. Also, we were thinking why are we using both sinon and jest for unit test cases. We should use only one, most likely jest. What do you think? Any reason why we are using sinon? Screenshot 2023-12-22 at 1 42 38 AM

🤷 I have barely worked with the backend unit tests or `sinon` personally, I'm not really familiar with that library. if jest can do all the same stuff then sure that makes sense to me, might be some work to swap it out but I'm all for removing dependencies when we can.

**Comment by ppratikcr7** [comment]
> > @danoswaltCL @bcb37 Now we are left with 4 backend packages to be updated. @RidhamShah is working on typedi, reflect-metadata and typeorm. We tried to update sinon, but there is some issues with unit test cases. Also, we were thinking why are we using both sinon and jest for unit test cases. We should use only one, most likely jest. What do you think? Any reason why we are using sinon? Screenshot 2023-12-22 at 1 42 38 AM
> 
> 🤷 I have barely worked with the backend unit tests or `sinon` personally, I'm not really familiar with that library. if jest can do all the same stuff then sure that makes sense to me, might be some work to swap it out but I'm all for removing dependencies when we can.

Okay, yeah you are right. jenn had worked on sinon based unit test cases. @danoswaltCL Can you create a ticket to remove sinon dependency and replace with jest based unit test cases?

**Review by VivekFitkariwala — APPROVED** [review]

**Pull request merged**
