### PR TITLE
Update TypeDoc entryPoints

### PR DESCRIPTION
**Pull request by zackcl**
This PR updates the TypeDoc entryPoints for generating the documentation markdown files. The existing entryPoints appear to be no longer valid and require updating. I have updated the entryPoints based on the warning messages received in the Terminal (as I run one after another). Please review to ensure they are correct.

- Before fix:
```
cuinjune@Zacks-MacBook-Air js % npm run docs:markdown       

> upgrade_client_lib@6.0.0 docs:markdown
> typedoc --options typedoc.json

[info] Loaded plugin typedoc-plugin-rename-defaults
[info] Loaded plugin typedoc-plugin-markdown
[warning] The entrypoint glob ./src/UpgradeClient.ts did not match any files.
[warning] The entrypoint glob ./src/identifiers did not match any files.
[warning] The entrypoint glob ./src/functions/getExperimentCondition.ts did not match any files.
[error] Unable to find any entry points. See previous warnings.
```

- After fix:
```
cuinjune@Zacks-MacBook-Air js % npm run docs:markdown                      

> upgrade_client_lib@6.1.0 docs:markdown
> typedoc --options typedoc.json

[info] Loaded plugin typedoc-plugin-rename-defaults
[info] Loaded plugin typedoc-plugin-markdown
[info] Documentation generated at ./docs
```

### CODE REVIEW

**Comment by danoswaltCL** [comment]
ah i see. one other thing is that for the gitbook we'd just need docs for the public parts, `ApiService` and `DataService` I think are all private implementations that the end user wouldn't need docs for.

Also should note that the need for typedoc predated chatgpt. It may be a moot technology now; the point was just to autogenerate documentation from code. It is probably easier to just use ai chat now.

**Comment by zackcl** [comment]
@danoswaltCL I understand, but I'm receiving these warnings if I run `npm run docs:markdown` without `ApiService` or `DataService`:

```
[warning] default, defined in ./src/ApiService/ApiService.ts, is referenced by Assignment/Assignment.Assignment.constructor.new Assignment.apiService but not included in the documentation.

[warning] DataService, defined in ./src/DataService/DataService.ts, is referenced by ApiService/ApiService.ApiService.constructor.new ApiService.dataService but not included in the documentation.
```

Do you suggest removing the `ApiService` and `DataService` despite the warnings? Or do you suggest removing the TypeDoc from our codebase? I think it's still good to be able to generate our documentation in a consistent format (maybe we can use this as a draft that LLM can improve upon).

**Comment by danoswaltCL** [comment]
ok, seems good to me then, I couldn't remember how that part worked

**Comment by zackcl** [comment]
@VivekFitkariwala suggested getting rid of the generated `clientlibs/js/docs` folder from the codebase by adding the path to `.gitignore`, instead, have the folder be generated on CI/CD actions (not sure if this is really needed though). I wonder what you think of this idea @danoswaltCL.

**Comment by zackcl** [comment]
@danoswaltCL @VivekFitkariwala I've added the `docs/` folder to the `.gitignore` file, and also deleted the existing docs folder from the repository. We can still locally generate the folder with `npm run docs:markdown`, it's just not included in the repository anymore. Please feel free to approve this PR.

**Pull request merged**
