### PR TITLE
🐛 Bugfix for missing query metric data columns in csv for first user with no logs

### PR DESCRIPTION
**Pull request by ppratikcr7**
This resolves issue #1690

### CODE REVIEW

**Comment by ppratikcr7** [comment]
Attaching a sample CSV export which now stores the query metric columns in case the first user has no query logs:

[pratik.prajapati@playpowerlabs.com_simpleExport2024-06-26T11:53:08.468Z.csv](https://github.com/user-attachments/files/15990400/pratik.prajapati%40playpowerlabs.com_simpleExport2024-06-26T11.53.08.468Z.csv)

**Comment by danoswaltCL** [comment]
@amurphy-cl can you verify that the export is as expected

**Comment by danoswaltCL** [comment]
@amurphy-cl when you get a chance, can you confirm that this improvement to the export is all good? then we can close out this ticket [pratik.prajapati@playpowerlabs.com_simpleExport2024-06-26T11:53:08.468Z.csv](https://github.com/user-attachments/files/15990400/pratik.prajapati%40playpowerlabs.com_simpleExport2024-06-26T11.53.08.468Z.csv)

**Comment by amurphy-cl** [comment]
This looks great except I'm not sure I understand where the labels from columns V, W, and X come from. Are those defined by the experimenter when setting up metrics?

**Comment by ppratikcr7** [comment]
> This looks great except I'm not sure I understand where the labels from columns V, W, and X come from. Are those defined by the experimenter when setting up metrics?

Yes, I had kept those names as query names while setting the experiment. Actually these format is already there in dev branch, this PR was created for handling an edge case where these column V, W and X which are the query metrics columns were not present in the export in case the first user in the csv rows was not having any metric logs. This is resolved now in this PR as you can check in this sample exported csv.

**Review by danoswaltCL — APPROVED** [review]

**Pull request merged**
