### PR TITLE
QA bugs of import/export segment csv resolved

### PR DESCRIPTION
**Pull request by Yagnik56**
resolved issue of removing empty row when we import members, same file not being imported second time and import button available on multiple empty rows.

### CODE REVIEW

**Comment by zackcl** [comment]
@Yagnik56 The "Import CSV" button no longer seems to work. It doesn't open the "Choose file" dialog for me on macOS. Does it work for you?

**Comment by Yagnik56** [comment]
@zackcl really sorry for that, after local QA in last moment I changed spelling mistake in ts file but forgot to do same in html.

**Comment by zackcl** [comment]
@Yagnik56 No worries, now the "Import CSV" button works, but clicking the button removes a row from table sometimes.

https://github.com/CarnegieLearningWeb/UpGrade/assets/90279765/8900d2fd-92a8-4eea-b903-18e727c8645d

**Comment by Yagnik56** [comment]
@zackcl that issue is resolved, you can go ahead with other QA.

**Comment by zackcl** [comment]
Everything works as expected now.

**Review by zackcl — APPROVED** [review]

**Pull request merged**
