### PR TITLE
:bug: Free groups

### PR DESCRIPTION
**Pull request by VivekFitkariwala**
On group change free enrollment groups.

It fixes some queries related to removing enrollments.

### CODE REVIEW

**Comment by bcb37** [comment]
> On group change free enrollment groups.
> 
> It fixes some queries related to removing enrollments.

I don't see how this removes enrollments on changes to groups. It looks like it removes _exclusions_ on changes to _working_ groups. In particular, entries seem to be being deleted from the `individual_exclusion` and `group_exclusion` tables in the db. How would the application break if those entries were not removed?

**Comment by VivekFitkariwala** [comment]
@bcb37 we don't have any test cases related to these edge cases and you are correct we should have test cases. It is a good idea to add more comments and update the naming. I will add/update this.
Thanks.

**Comment by RidhamShah** [comment]
@bcb37 added test cases for the working group change scenarios. You can re-review this PR.

**Comment by bcb37** [comment]
> @bcb37 we don't have any test cases related to these edge cases and you are correct we should have test cases. It is a good idea to add more comments and update the naming. I will add/update this. Thanks.

The test cases were very helpful to me in understanding this issue. However, shouldn't the group exclusions/enrollments be added back if the group membership is reverted back to the original value?

**Review by bcb37 — COMMENTED** [review]
Just one more question

**Review by bcb37 — APPROVED** [review]

**Pull request merged**
