### PR TITLE
Solving snackbar errors

### PR DESCRIPTION
**Pull request by RidhamShah**

### CODE REVIEW

**Comment by zackcl** [comment]
Is there a reason for replacing the `MatSnackBar` with `angular2-notifications`? I'm just curious.

**Comment by zackcl** [comment]
I've updated the design a little bit. Please let me know if you want me to update it further.

Screenshot 2023-10-23 at 6 17 25 PM

**Comment by amurphy-cl** [comment]
This looks great

**Comment by ppratikcr7** [comment]
> Is there a reason for replacing the `MatSnackBar` with `angular2-notifications`? I'm just curious.

We were using both of them earlier. For network call errors we were using `angular2-notifications` and for success we were using `MatSnackBar`. But, now we decided to use only a single package `angular2-notifications` as it provides a nice queue system to stack the errors/success etc toast messages on top of one another to give a better readability. Also, the icons in the toast message is also good to have.

**Comment by ppratikcr7** [comment]
> I've updated the design a little bit. Please let me know if you want me to update it further.
> 
> Screenshot 2023-10-23 at 6 17 25 PM

There are various color coding for success/error/warn/info message type. Can you help out with deciding the correct css color and icons for them? @RidhamShah Maybe you can drop the screenshot with all of them showing at once?

**Comment by RidhamShah** [comment]
image
These are the updated snackBars for Success, Error, Warn, Info

**Pull request closed without merging**
