### PR TITLE
Update Java Client Lib assign response with order field

### PR DESCRIPTION
**Pull request by kawcl**
add the "order" field in the response object

### CODE REVIEW

**Comment by jerith666** [comment]
looks good except it needs a `pom.xml` version increment.

**Review by jerith666 — CHANGES_REQUESTED** [review]
looks good except you need a `pom.xml` version increment

**Comment by kawcl** [comment]
> looks good except you need a `pom.xml` version increment

🤦  .. is there a pattern we follow for these version increments? what happens when two or more PRs are updating to the same version? is that fine?

**Comment by jerith666** [comment]
Alas, we don't have good answers to either of those questions.

We should probably rev to 1.0 at some point, and then start following https://semver.org, but I'm not sure when's the right time for that.  Though honestly, now is probably fine; semver FAQ says:

> How do I know when to release 1.0.0?
> If your software is being used in production, it should probably already be 1.0.0.

... and we are using it in production.  :)

If you put a comment (like `<version>0.10</version> <!-- 0.10 adds the order field to the response object -->`), then it'll produce a conflict unless the other branch has added that exact same comment, which is highly unlikely.  That's probably the best strategy I can recommend.

**Comment by kawcl** [comment]
I updated the version and added in the a comment for now

**Review by jerith666 — APPROVED** [review]

**Comment by jerith666** [comment]
Looks good now, thanks!

**Review by ppratikcr7 — APPROVED** [review]

**Review by VivekFitkariwala — APPROVED** [review]

**Pull request merged**
