### PR TITLE
🐛 Resolved sorting of experiment list with mixed cases

### LINKED ISSUE #988: Experiment List Sorting order is off for mixed lowercase and uppercase experiment names
**Version where bug was found:**
e.g "5.0.1"

**Describe the bug**
Experiment List Sorting order is off for mixed lowercase and uppercase experiment names on the home screen.

**To Reproduce**
1. Add few 5-10 experiments.
2. View the order. It should be as per descending name.

**Expected behavior**
Sorting order should be descending name.

**Screenshots**
Screenshot 2023-08-17 at 4 24 47 PM

### PR DESCRIPTION
**Pull request by ppratikcr7**
Resolves #988

Earlier. the fix was working fine. But, the experiment list changed after archived state experiments and that new list had to be sorted as well.

### CODE REVIEW

**Comment by zackcl** [comment]
I tested this and sorting seems to work as expected, including the Archived experiments. Let me know if there's any other things that should be tested.

Screenshot 2023-11-16 at 6 02 33 PM
Screenshot 2023-11-16 at 6 05 31 PM

**Comment by ppratikcr7** [comment]
> I tested this branch and sorting seems to work as expected, including the Archived experiments. Let me know if there's any other things that should be tested.
> 
> Screenshot 2023-11-16 at 6 02 33 PM Screenshot 2023-11-16 at 6 05 31 PM

@zackcl I guess then you can approve and merge this PR.

**Review by zackcl — APPROVED** [review]

**Comment by ppratikcr7** [comment]
QA: @zackcl Can you please QA this?

**Comment by zackcl** [comment]
QA: Passed

**Pull request merged**
