### PR TITLE
removed disable on context change in experiment edit modal

### PR DESCRIPTION
**Pull request by Yagnik56**
This PR removes the disabling of the save button for the experiment edit modal when the context changes and removes the code to clear the design page data on the same.

Also, show a warning on the design type change of the experiment to let the user know why save has been disabled.
image

### CODE REVIEW

**Comment by amurphy-cl** [comment]
Suggested changes to error messages: 

- "Changing the Design Type will clear all fields in Experiment Design. Review before saving."
- "Changing the App Context will clear all fields in Experiment Design, Participants, and Metrics. Review before saving."

**Comment by danoswaltCL** [comment]
> Suggested changes to error messages:
> 
> * "Changing the Design Type will clear all fields in Experiment Design. Review before saving."
> * "Changing the App Context will clear all fields in Experiment Design, Participants, and Metrics. Review before saving."

Changing the app context will not clear the fields in the Design step in this change though, I believe that's what was decided. @amurphy-cl @zackcl

**Comment by zackcl** [comment]
Here are my suggested messages:

- "Changing the Design Type will clear all fields in the Design step. Please review before saving."
- "Changing the App Context will clear all fields in the Participants and Metrics steps. Please review before saving."

**Comment by ppratikcr7** [comment]
@zackcl As discussed in the meet you can add the messages and remove logging checkbox as yagnik is on leave.

**Comment by zackcl** [comment]
@danoswaltCL @bcb37 I made a commit (https://github.com/CarnegieLearningWeb/UpGrade/pull/2094/commits/cdae59f186b8d40915624452011e211eab669bf0) that removes the "Logging" checkbox and the unused "enableSave" variables (not sure why they existed), and displays the warning message when the "App Context" or the "Design Type" changes once the Overview step has been completed. Please feel free to review and test it.

**Review by danoswaltCL — APPROVED** [review]

**Pull request merged**
