### PR TITLE
replaced add include/exclude list button to Add

### PR DESCRIPTION
**Pull request by Yagnik56**
This PR replaced the add include/exclude list button with a simple Add as we discussed.

### CODE REVIEW

**Comment by zackcl** [comment]
@Yagnik56 @danoswaltCL Are we sure about this? If we simply make the button labels "Add", shouldn't we also update the "Add Feature Flag" and "Add Segment" button labels for consistency?

**Comment by danoswaltCL** [comment]
🤷‍♂️ I have no opinion, just making a ticket to remember Steve's suggestion.

**Comment by zackcl** [comment]
@danoswaltCL How about we ask one more time before we merge this? Or maybe I can create and share two separate design images so that we can compare.

**Comment by zackcl** [comment]
Closing this as we decided to keep the button labels for now.

**Pull request closed without merging**
