### PR TITLE
🐞  Hotfix/Split getValidExperiment queries into 3 sub queries to reduce latency against Release V4

### PR DESCRIPTION
**Pull request by ppratikcr7**
This PR contains changes for splitting the large query in getValidExperiments() and getValidExperimentsWithPreview() called within the `assign` api call for release V4. Please refer the load testing [results](https://docs.google.com/document/d/14F1XxB6QifEW-q9XhqVgWg7Pgb0qJbnqlNg6TxgGxNE/edit?usp=sharing).

### CODE REVIEW

**Comment by danoswaltCL** [comment]
Hey @ppratikcr7 thank for this. Can you put it into the `release/v5` branch? That's what is currently in production.

**Comment by ppratikcr7** [comment]
> Hey @ppratikcr7 thank for this. Can you put it into the `release/v5` branch? That's what is currently in production.

Oh okay, I thought we discussed to first test on releasev4 and then move to v5.

**Comment by danoswaltCL** [comment]
ok, hm maybe that does make sense so we can compare difference, I don't remember what was said about testing on 4 but that is worth a try actually, sry to ask you to change it again, yes we can put this against 4 and try it out to compare.

**Comment by ppratikcr7** [comment]
@danoswaltCL [PR](https://github.com/CarnegieLearningWeb/UpGrade/pull/1083) against release V5.

**Comment by danoswaltCL** [comment]
This can be closed as v5 is looking stable otherwise, I think we are done with v4.

**Pull request closed without merging**
